# Generated by Django 5.2.13 on 2026-05-21 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0081_caseintakeprocess_has_urgency_declaration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carecategorymain',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='carecategorymain',
            name='visible_in_mvp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carecategorysubcategory',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='carecategorysubcategory',
            name='visible_in_mvp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='contractregio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractregio_intakes', to='contracts.regionalconfiguration', verbose_name='Contractregio'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='escalatie_regio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalatie_intakes', to='contracts.regionalconfiguration', verbose_name='Escalatieregio'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='herkomst_gemeente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_intake_processes', to='contracts.municipalityconfiguration', verbose_name='Herkomstgemeente'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='plaatsingsregio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaatsingsregio_intakes', to='contracts.regionalconfiguration', verbose_name='Plaatsingsregio'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='requires_revalidation',
            field=models.BooleanField(default=False, help_text='Wordt automatisch geactiveerd wanneer route- of regiogrenzen verschuiven.', verbose_name='Herbeoordeling vereist'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='responsibility_last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Laatste herbeoordeling'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='responsibility_reason',
            field=models.TextField(blank=True, verbose_name='Verantwoordingsreden'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='verantwoordelijke_gemeente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibility_intake_processes', to='contracts.municipalityconfiguration', verbose_name='Verantwoordelijke gemeente'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='verblijfsgemeente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residence_intake_processes', to='contracts.municipalityconfiguration', verbose_name='Verblijfsgemeente'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='zorgregio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zorgregio_intakes', to='contracts.regionalconfiguration', verbose_name='Zorgregio'),
        ),
        migrations.AddField(
            model_name='municipalityconfiguration',
            name='active',
            field=models.BooleanField(db_index=True, default=True, help_text='Afgeleide vlag op basis van status; gebruikt voor snelle filtering.', verbose_name='Actief'),
        ),
        migrations.AddField(
            model_name='municipalityconfiguration',
            name='brp_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='BRP-code'),
        ),
        migrations.AddField(
            model_name='municipalityconfiguration',
            name='budget_owner',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Budgetverantwoordelijke'),
        ),
        migrations.AddField(
            model_name='municipalityconfiguration',
            name='contract_policies',
            field=models.JSONField(blank=True, default=list, verbose_name='Contractpolicies'),
        ),
        migrations.AddField(
            model_name='municipalityconfiguration',
            name='woonplaatsbeginsel_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='woonplaatsbeginsel_municipalities', to=settings.AUTH_USER_MODEL, verbose_name='Woonplaatsbeginsel contact'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='target_care_subcategories',
            field=models.ManyToManyField(blank=True, related_name='provider_profiles', to='contracts.carecategorysubcategory', verbose_name='Specifieke zorgbehoeften'),
        ),
        migrations.AddField(
            model_name='providerregiodekking',
            name='capaciteit',
            field=models.PositiveIntegerField(blank=True, help_text='Indicatieve beschikbare capaciteit in deze regiodekking.', null=True, verbose_name='Capaciteit'),
        ),
        migrations.AddField(
            model_name='providerregiodekking',
            name='crisis_beschikbaar',
            field=models.BooleanField(default=False, verbose_name='Crisis beschikbaar'),
        ),
        migrations.AddField(
            model_name='providerregiodekking',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notities'),
        ),
        migrations.AddField(
            model_name='providerregiodekking',
            name='wachtlijst_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('BEPERKT', 'Beperkt'), ('GESLOTEN', 'Gesloten')], default='OPEN', max_length=20, verbose_name='Wachtlijststatus'),
        ),
        migrations.AddField(
            model_name='regionalconfiguration',
            name='active',
            field=models.BooleanField(db_index=True, default=True, help_text='Afgeleide vlag op basis van status; gebruikt voor snelle filtering.', verbose_name='Actief'),
        ),
        migrations.AddField(
            model_name='regionalconfiguration',
            name='escalatie_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalatie_regios', to=settings.AUTH_USER_MODEL, verbose_name='Escalatiecontact'),
        ),
        migrations.AlterField(
            model_name='carecase',
            name='source_system_id',
            field=models.IntegerField(blank=True, default=0, help_text='Optional legacy upstream system key (production Postgres drift).', null=True),
        ),
        migrations.AlterField(
            model_name='caseintakeprocess',
            name='care_category_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes_main', to='contracts.carecategorymain', verbose_name='Zorgbehoefte categorie'),
        ),
        migrations.AlterField(
            model_name='caseintakeprocess',
            name='care_category_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes_sub', to='contracts.carecategorysubcategory', verbose_name='Specifieke zorgbehoefte'),
        ),
        migrations.AlterField(
            model_name='caseintakeprocess',
            name='preferred_region_type',
            field=models.CharField(choices=[('GEMEENTELIJK', 'Gemeentelijk'), ('JEUGDREGIO', 'Jeugdregio'), ('ROAZ', 'ROAZ'), ('GGD', 'GGD'), ('ZORGKANTOOR', 'Zorgkantoor'), ('CUSTOM', 'Aangepast')], default='GEMEENTELIJK', max_length=20, verbose_name='Voorkeur regiotype'),
        ),
        migrations.AlterField(
            model_name='caseintakeprocess',
            name='target_completion_date',
            field=models.DateField(verbose_name='Streefdatum matching'),
        ),
        migrations.AlterField(
            model_name='regionalconfiguration',
            name='region_type',
            field=models.CharField(choices=[('GEMEENTELIJK', 'Gemeentelijk'), ('JEUGDREGIO', 'Jeugdregio'), ('ROAZ', 'ROAZ'), ('GGD', 'GGD'), ('ZORGKANTOOR', 'Zorgkantoor'), ('CUSTOM', 'Aangepast')], db_index=True, default='GEMEENTELIJK', max_length=20, verbose_name='Regiotype'),
        ),
    ]
