# Generated by Django 5.2.13 on 2026-05-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0084_caseintakeprocess_urgency_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='external_handoff_reference',
            field=models.CharField(blank=True, default='', help_text='Veilige verwijzing naar een extern systeem of een beveiligde uitwisseling. Geen persoonsgegevens.', max_length=500, verbose_name='Externe handoffreferentie'),
        ),
        migrations.AlterField(
            model_name='caseintakeprocess',
            name='assessment_summary',
            field=models.TextField(blank=True, help_text='Pseudonieme beschrijving van de casus. Geen namen, adressen, contactgegevens of BSN.', verbose_name='Intake samenvatting'),
        ),
        migrations.AlterField(
            model_name='caseintakeprocess',
            name='description',
            field=models.TextField(blank=True, help_text='Alleen operationele context zonder direct herleidbare persoonsgegevens.', verbose_name='Aanvullende opmerkingen'),
        ),
        migrations.AlterField(
            model_name='caseintakeprocess',
            name='title',
            field=models.CharField(help_text='Gebruik een pseudoniem of operationeel label. Geen naam, initialen of andere identificerende gegevens.', max_length=200, verbose_name='Casuslabel'),
        ),
    ]
