# Generated by Django 5.2.13 on 2026-06-20 14:20

import contracts.models.care_case
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0087_classification_model_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caseintakeprocess',
            name='intake_appointment_at',
            field=models.DateTimeField(blank=True, help_text='Datum en tijdstip van de geplande intake bij de aanbieder.', null=True, verbose_name='Geplande intake-afspraak'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='intake_appointment_conducted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_intake_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Intakecoordinator'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='intake_appointment_location',
            field=models.CharField(blank=True, default='', help_text='Locatieomschrijving zonder direct herleidbare persoonsgegevens.', max_length=200, verbose_name='Locatie intake-afspraak'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='intake_appointment_notes',
            field=models.TextField(blank=True, default='', help_text='Voorbereiding of agendapunten; geen medische of herleidbare informatie.', verbose_name='Notities intake-afspraak'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.care_case._document_upload_path),
        ),
        migrations.AlterField(
            model_name='placementrequest',
            name='placement_quality_reason_code',
            field=models.CharField(default='NONE', max_length=30, verbose_name='Redencode plaatsingskwaliteit'),
        ),
    ]
